Carbon.AdminSite/Pages/Carbon/Account/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Carbon.AdminSite.Pages.Account
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Carbon.AdminSite/Pages/Carbon/Account/ConfirmEmail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Carbon.Api.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Carbon.AdminSite.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public ConfirmEmailModel(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{userId}'.");
            }

            var result = await _userManager.ConfirmEmailAsync(user, code);
            if (!result.Succeeded)
            {
                throw new ApplicationException($"Error confirming email for user with ID '{userId}':");
            }

            return Page();
        }
    }
}

Carbon.AdminSite/Pages/Carbon/Account/ExternalLogin.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Carbon.Api.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Carbon.AdminSite.Pages.Account
{
    public class ExternalLoginModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<ExternalLoginModel> _logger;

        public ExternalLoginModel(
            SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager,
            ILogger<ExternalLoginModel> logger)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string LoginProvider { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public IActionResult OnGetAsync()
        {
            return RedirectToPage("./Login");
        }

        public IActionResult OnPost(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = Url.Page("./ExternalLogin", pageHandler: "Callback", values: new { returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return new ChallengeResult(provider, properties);
        }

        public async Task<IActionResult> OnGetCallbackAsync(string returnUrl = null, string remoteError = null)
        {
            if (remoteError != null)
            {
                ErrorMessage = $"Error from external provider: {remoteError}";
                return RedirectToPage("./Login");
            }
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                return RedirectToPage("./Login");
            }

            // Sign in the user with this external login provider if the user already has a login.
            var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor : true);
            if (result.Succeeded)
            {
                _logger.LogInformation("{Name} logged in with {LoginProvider} provider.", info.Principal.Identity.Name, info.LoginProvider);
                return LocalRedirect(Url.GetLocalUrl(returnUrl));
            }
            if (result.IsLockedOut)
            {
                return RedirectToPage("./Lockout");
            }
            else
            {
                // If the user does not have an account, then ask the user to create an account.
                ReturnUrl = returnUrl;
                LoginProvider = info.LoginProvider;
                if (info.Principal.HasClaim(c => c.Type == ClaimTypes.Email))
                {
                    Input = new InputModel
                    {
                        Email = info.Principal.FindFirstValue(ClaimTypes.Email)
                    };
                }
                return Page();
            }
        }

        public async Task<IActionResult> OnPostConfirmationAsync(string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                // Get the information about the user from the external login provider
                var info = await _signInManager.GetExternalLoginInfoAsync();
                if (info == null)
                {
                    throw new ApplicationException("Error loading external login information during confirmation.");
                }
                var user = new ApplicationUser { UserName = Input.Email, Email = Input.Email };
                var result = await _userManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    result = await _userManager.AddLoginAsync(user, info);
                    if (result.Succeeded)
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        _logger.LogInformation("User created an account using {Name} provider.", info.LoginProvider);
                        return LocalRedirect(Url.GetLocalUrl(returnUrl));
                    }
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            ReturnUrl = returnUrl;
            return Page();
        }
    }
}

Carbon.AdminSite/Pages/Carbon/Account/ForgotPassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Carbon.Api.Data;
using Carbon.Api.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Carbon.AdminSite.Pages.Account
{
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;

        public ForgotPasswordModel(UserManager<ApplicationUser> userManager, IEmailSender emailSender)
        {
            _userManager = userManager;
            _emailSender = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Input.Email);
                if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return RedirectToPage("./ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please 
                // visit https://go.microsoft.com/fwlink/?LinkID=532713
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                var callbackUrl = Url.ResetPasswordCallbackLink(user.Id, code, Request.Scheme);
                await _emailSender.SendResetPasswordAsync(Input.Email, callbackUrl);
                return RedirectToPage("./ForgotPasswordConfirmation");
            }

            return Page();
        }
    }
}

Carbon.AdminSite/Pages/Carbon/Account/ForgotPasswordConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Carbon.AdminSite.Pages.Account
{
    public class ForgotPasswordConfirmation : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Carbon.AdminSite/Pages/Carbon/Account/Lockout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Carbon.AdminSite.Pages.Account
{
    public class LockoutModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Carbon.AdminSite/Pages/Carbon/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Carbon.Api.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Carbon.AdminSite.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<ApplicationUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            ReturnUrl = returnUrl;

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: true);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(Url.GetLocalUrl(ReturnUrl));
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

Carbon.AdminSite/Pages/Carbon/Account/ResetPasswordConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Carbon.AdminSite.Pages.Account
{
    public class ResetPasswordConfirmationModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Carbon.AdminSite/Pages/Carbon/Account/SignedOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

public class SignedOutModel : PageModel
{
    public IActionResult OnGet()
    {
        if (User.Identity.IsAuthenticated)
        {
            // Redirect to home page if the user is authenticated.
            return RedirectToPage("/Index");
        }

        return Page();
    }
}

Carbon.AdminSite/Pages/Carbon/Editor.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Carbon.Api.Data;
using Carbon.Api.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Carbon.AdminSite.Pages
{
    [Authorize]
    public class EditorModel : PageModel
    {
        [BindProperty]
        public Post Post { get; set; }

        [BindProperty]
        public bool Edited { get; set; } = false;

        private readonly BlogContext _blogContext;
        private readonly UserManager<ApplicationUser> _userManager;
        private SignInManager<ApplicationUser> _signInManager;

        public EditorModel(BlogContext context, UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            _blogContext = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        

        public async Task<IActionResult> OnGetEditorAsync(int id)
        {
            Post = await _blogContext.Posts
                .Include(P => P.PostTags)
                .SingleOrDefaultAsync(P => P.Id == id);
                


            if (Post == null)
            {
                return RedirectToPage("/Carbon/Index");
            }

            Edited = true;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }


            var user = await _userManager.GetUserAsync(User);
            Post.CreateTime = DateTime.Now;
            Post.Author = user;
            Post.PostTags = new List<PostTag>();
            
            var returnedTag = _blogContext.Tags.FirstOrDefault(t => t.Id == 2);

            Post.PostTags.Add(new PostTag
            {
                Post = Post,
                Tag = returnedTag
            });
            
            _blogContext.Posts.Add(Post);


            

            await _blogContext.SaveChangesAsync();
            return RedirectToPage("/Carbon/Index");
        }

        public async Task<IActionResult> OnPostEditAsync(int id)
        {
            var user = await _userManager.GetUserAsync(User);


            if (!ModelState.IsValid)
            {
                return Page();
            }
            
            var returnedTag = _blogContext.Tags.FirstOrDefault(t => t.Id == 1);

            var postToUpdate = await _blogContext.Posts
                .Include(P => P.PostTags)
                .SingleAsync(P => P.Id == id);

            postToUpdate.UpdatedTime = DateTime.Now;
            postToUpdate.PostTags.Add(new PostTag { Post = postToUpdate, Tag = returnedTag });
            
            
            if (await TryUpdateModelAsync<Post>(
                postToUpdate,
                "post",
                p => p.UpdatedTime, p => p.Title, p => p.Content, p => p.PostTags))
            {
                
                await _blogContext.SaveChangesAsync();
                return RedirectToPage("/Carbon/Index");
            }


            return RedirectToPage("/Carbon/Index");
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var post = await _blogContext.Posts.FindAsync(id);

            if (post != null)
            {
                _blogContext.Posts.Remove(post);
                await _blogContext.SaveChangesAsync();
            }

            return RedirectToPage("/Carbon/Index");
        }
    }
}

Carbon.AdminSite/Pages/Carbon/Editor.cshtml
@page
@using Carbon.AdminSite.Pages
@using Carbon.Api.Data
@using Microsoft.AspNetCore.Identity
@model Carbon.AdminSite.Pages.EditorModel
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Editor";
}

<div>
    <div asp-validation-summary="All"></div>
    <form method="POST">
        <section class="post-title-section">
            <div>
                <textarea asp-for="Post.Title" class="post-title" placeholder="Title"></textarea>
                <span asp-validation-for="Post.Title" ></span>
            </div>
        </section>
        <section class="post-section">
            <div>
                <textarea asp-for="Post.Content" class="post-content" placeholder="Content"></textarea>
                <span asp-validation-for="Post.Content" ></span>
            </div>
        </section>
       
        
        @if (Model.Edited)
        {
            <button type="submit" class="btn btn-secondary" asp-page-handler="edit" asp-route-id="@Model.Post.Id">Save</button>
            
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                Delete
            </button>
            
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Delete Post</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete this post?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-danger" asp-page-handler="delete" 
                                    asp-route-id="@Model.Post.Id">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        }
        else
        {
            <button type="submit" class="btn btn-secondary" asp-page-handler="create">Save</button>
        }
    </form>
</div>

Carbon.AdminSite/Pages/Carbon/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div>
    <a class="btn btn-default" asp-page="/Carbon/Editor">Create</a>
    @foreach (var post in Model.Posts)
    {
        <h1><a asp-page="/Carbon/Editor" asp-page-handler="editor" asp-route-id="@post.Id">@post.Title</a></h1>
        <p>@post.Content</p>
    }
</div>

Carbon.AdminSite/Pages/Carbon/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Carbon</title>

    <environment include="Development">
@*        <link rel="stylesheet" href="~/lib/materialize/dist/css/materialize.css"/>*@
        <link rel="stylesheet" href="~/css/site.css"/>
        <link href="https://fonts.googleapis.com/css?family=Muli:300|Roboto:300,400" rel="stylesheet"> 
    </environment>
    <environment exclude="Development">
@*        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"*@
@*              asp-fallback-href="~/lib/materialize/dist/css/materialize.min.css"*@
@*              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>*@
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
        <link href="https://fonts.googleapis.com/css?family=Muli:300|Roboto:300,400" rel="stylesheet"> 
    </environment>
</head>
<body>
@await Html.PartialAsync("_LoginPartial")
<div class="body-content">
    @RenderBody()
</div>
<footer>
    <p>&copy; 2017 - Carbon</p>
</footer>

<environment include="Development">
    <script src="~/components/carbon.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    @*    <script src="~/lib/materialize/dist/js/materialize.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/webcomponentsjs/webcomponents-lite.js"></script>
</environment>
<environment exclude="Development">
    <script src="~/components/carbon.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    @*    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"*@
    @*            asp-fallback-src="~/lib/materialize/dist/js/materialize.min.js"*@
    @*            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"*@
    @*            crossorigin="anonymous"*@
    @*            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">*@
    @*    </script>*@
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", required: false)
</body>
</html>